### ISSUE TITLE
Stash App Crashes - Fatal Exception - Null object reference in serveraccess.java

### ISSUE THREAD

**Issue by kkhetarpal** [Alok-Sharma/Stash#49]
Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
![error_in_serveraccess](https://cloud.githubusercontent.com/assets/7235682/11321878/71407038-908d-11e5-8162-1803fb8d77a4.png)

**Comment by Alok-Sharma** [comment]
Fixed. 59bbce48e3de59162fd331bdf3d3517390403322
