### ISSUE TITLE
View Stash- back button doesn't work

### ISSUE THREAD

**Issue by kkhetarpal** [Alok-Sharma/Stash#52]
When you are inside a stash(via view stash), and you click on the back navigation arrow in the action bar, that has no effect, either that is not needed(check with designs) or that should be functional.
![view_stash_backbutton](https://cloud.githubusercontent.com/assets/7235682/11322080/8027cfc4-9097-11e5-9806-9e88d8dff7cd.png)

**Comment by Alok-Sharma** [comment]
Seems to have been caused due to adding the overflow menu (for delete stash). Will fix.

**Comment by Alok-Sharma** [comment]
Fixed.
aed09e89ec1d050c181c3f1c940cd2c0bf03adc9
